name: project
dependencies:
- _nb_ext_conf=0.3.0=py35_0
- anaconda-client=1.6.2=py35_0
- bleach=1.5.0=py35_0
- click=6.7=py35_0
- clyent=1.2.2=py35_0
- cycler=0.10.0=py35_0
- dbus=1.10.10=0
- decorator=4.0.11=py35_0
- entrypoints=0.2.2=py35_1
- expat=2.1.0=0
- flask=0.12=py35_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.6.0=np112py35_2
- hdf5=1.8.17=1
- html5lib=0.999=py35_0
- icu=54.1=0
- ipykernel=4.5.2=py35_0
- ipython=5.3.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_1
- itsdangerous=0.24=py35_0
- jbig=2.1=0
- jinja2=2.9.5=py35_0
- jpeg=9b=0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=5.0.0=py35_0
- jupyter_console=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- llvmlite=0.16.0=py35_0
- markupsafe=0.23=py35_2
- matplotlib=2.0.0=np112py35_0
- mistune=0.7.3=py35_0
- mkl=2017.0.1=0
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=5.1.1=py35_0
- nbformat=4.3.0=py35_0
- nbpresent=3.0.2=py35_0
- notebook=4.3.1=py35_0
- numba=0.31.0=np112py35_0
- numpy=1.12.0=py35_0
- olefile=0.44=py35_0
- openssl=1.0.2k=1
- pandocfilters=1.4.1=py35_0
- path.py=10.1=py35_0
- pcre=8.39=1
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=4.0.0=py35_1
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.9=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.2.0=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.3=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- pyyaml=3.12=py35_0
- pyzmq=16.0.2=py35_0
- qt=5.6.2=3
- qtconsole=4.2.1=py35_1
- readline=6.2=2
- requests=2.13.0=py35_0
- scikit-learn=0.18.1=np112py35_1
- scipy=0.18.1=np112py35_1
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- testpath=0.3=py35_0
- tk=8.5.18=0
- tornado=4.4.2=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- werkzeug=0.11.15=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - appdirs==1.4.2
  - ipython-genutils==0.1.0
  - jupyter-client==5.0.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - keras==1.2.2
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - packaging==16.8
  - prompt-toolkit==1.0.9
  - protobuf==3.2.0
  - tensorflow==1.0.0
  - theano==0.8.2
prefix: /home/ms/programs/miniconda3/envs/project

